### ISSUE TITLE
Problem with serializing/unserializing of ArrayObject on PHP 7.4

### ISSUE THREAD

**Issue by syberon** [zendframework/zend-stdlib#104]
I found the problem that related to PHP 7.4 session unserializing. I made some tests and found that if some class (Zend\Stdlib\ArrayObject in this case) implements Serializable interface and has some property (object of stdClass for example) it failed to decode if stored in session.

### Code to reproduce the issue

```
include "../vendor/autoload.php";

// Shared object that acts as property of two another objects stored in session
$testPropertyObj = new stdClass();
$testPropertyObj->name = 'test';

// Two instances of \SerializableClass that shares property
$sessionObject = [
    'obj1' => new \Zend\Stdlib\ArrayObject(['custom' => $testPropertyObj]),
    'obj2' => new \Zend\Stdlib\ArrayObject(['custom' => $testPropertyObj])
];

session_start();

$_SESSION = $sessionObject;
```

### Expected results

On the second run the stored in session array of objects should should be available in $_SESSION array.

### Actual results

On the second run the script rise errors then tries to restore second object of session.
```
Notice: unserialize(): Error at offset 41 of 222 bytes in C:\SERVER\projects\zf3\mt4\vendor\zendframework\zend-stdlib\src\ArrayObject.php on line 409

Notice: Trying to access array offset on value of type bool in C:\SERVER\projects\zf3\mt4\vendor\zendframework\zend-stdlib\src\ArrayObject.php on line 412

Notice: Trying to access array offset on value of type bool in C:\SERVER\projects\zf3\mt4\vendor\zendframework\zend-stdlib\src\ArrayObject.php on line 413

Warning: session_start(): Failed to decode session object. Session has been destroyed in C:\SERVER\projects\zf3\mt4\public_html\test.php on line 16

Fatal error: Uncaught Zend\Stdlib\Exception\InvalidArgumentException: Passed variable is not an array or object, using empty array instead in C:\SERVER\projects\zf3\mt4\vendor\zendframework\zend-stdlib\src\ArrayObject.php:184 Stack trace: #0 C:\SERVER\projects\zf3\mt4\vendor\zendframework\zend-stdlib\src\ArrayObject.php(413): Zend\Stdlib\ArrayObject->exchangeArray(NULL) #1 [internal function]: Zend\Stdlib\ArrayObject->unserialize('a:4:{s:7:"stora...') #2 C:\SERVER\projects\zf3\mt4\public_html\test.php(16): session_start() #3 {main} thrown in C:\SERVER\projects\zf3\mt4\vendor\zendframework\zend-stdlib\src\ArrayObject.php on line 184

```

This makes impossible to use Zend_Authentication (and other components that uses ArrayObject to store some data in session) with PHP 7.4 because in stores identity as Zend ArrayObject.

When i remove implementing of Serializable interface from ArrayObject class declaration it starts to work normally in PHP 7.4

**Comment by michalbundyra** [comment]
Ref: https://github.com/zendframework/zend-session/issues/126

Seems to be a bug in PHP 7.4. See: https://bugs.php.net/bug.php?id=79031
